services:
  brenda:
    build: .
    container_name: brenda
    expose:
      - "8501"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - /root/.acme.sh/brenda.oekrice.com_ecc:/etc/letsencrypt/live/brenda.oekrice.com:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - brenda
    networks:
      - webnet

networks:
  webnet:
